### ISSUE TITLE
hmr reloads browser content on changes to styles/main.scsss but not for changes to server/index.js

### ISSUE THREAD

**Issue by laurencefass** [cilliemalan/webpack-hmr-example#1]
i'm running this as a test site here: https://socket.syntapse.co.uk/express-hmr/

i'm not sure if this is a bug in code, plugin, or a configuration issue.

i was expecting to be able to make changes to server/index.js and see changes in the browser but there is no reload when i change index.js text.

please note this works as expected when making changes to scss. i.e. i change main.scss and the changes are reflected in the browser.

Even though index.js does not update are changes are being logged on the hmr log at https://socket.syntapse.co.uk/express-hmr/__webpack_hmr

i'm not sure if that's by design or because somethings broken. im happy to supply more info on request.

**Comment by cilliemalan** [comment]
Note that changes to server side code will not reload the client application. It will, however, reload the server modules, so if the browser makes another request it will execute against the new code.

However there may be something broken. Who knows. It's been a few years... If you're making a new react app, using [something newer](https://reactjs.org/docs/create-a-new-react-app.html) may work better for you.

If my off-the-cuff answer doesn't help, let me know.

**Comment by laurencefass** [comment]
this is the most minimal and simple example ive found so i would like to try to make it work if possible. i've updated packages to latest versions.

Does your explanation mean that client/index.js save file SHOULD cause a reload?  It is being bundled to output so that's what i was expecting.

**Comment by laurencefass** [comment]
added this to my files and its all working. thanks for feedback.
```

if (module.hot) {
    module.hot.accept();
}
```
